global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
global using System.Text;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Swashbuckle.AspNetCore.Annotations;
global using System.Net;
global using CodecoolApi.Services.Dtos.User;
global using CodecoolApi.Services.Services.Interfaces;
global using CodecoolApi.Services.Dtos.Author;
global using CodecoolApi.Services.Dtos.EducationalMaterial;
global using CodecoolApi.Services.Dtos.EducationalMaterialReview;
global using CodecoolApi.Services.Dtos.EducationalMaterialType;
global using CodecoolApi.Data.Context;
global using CodecoolApi.Data.DAL;
global using CodecoolApi.Data.DAL.Interfaces;

